
package be.alphacredit.tests;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-03-14T13:33:57.363+01:00
 * Generated source version: 2.7.18
 */

@WebFault(name = "testStringFault", targetNamespace = "http://www.alphacredit.be/tests/")
public class TestOperationException extends Exception {
    
    private be.alphacredit.tests.TestStringFault testStringFault;

    public TestOperationException() {
        super();
    }
    
    public TestOperationException(String message) {
        super(message);
    }
    
    public TestOperationException(String message, Throwable cause) {
        super(message, cause);
    }

    public TestOperationException(String message, be.alphacredit.tests.TestStringFault testStringFault) {
        super(message);
        this.testStringFault = testStringFault;
    }

    public TestOperationException(String message, be.alphacredit.tests.TestStringFault testStringFault, Throwable cause) {
        super(message, cause);
        this.testStringFault = testStringFault;
    }

    public be.alphacredit.tests.TestStringFault getFaultInfo() {
        return this.testStringFault;
    }
}
