package be.alphacredit.tests;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-04-06T17:28:09.665+02:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "TestService", 
                  wsdlLocation = "WEB-INF/wsdl/test.wsdl",
                  targetNamespace = "http://www.alphacredit.be/tests/") 
public class TestService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.alphacredit.be/tests/", "TestService");
    public final static QName TestServicePort = new QName("http://www.alphacredit.be/tests/", "TestServicePort");
    static {
        URL url = TestService.class.getResource("WEB-INF/wsdl/test.wsdl");
        if (url == null) {
            url = TestService.class.getClassLoader().getResource("WEB-INF/wsdl/test.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(TestService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "WEB-INF/wsdl/test.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public TestService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TestServicePortType
     */
    @WebEndpoint(name = "TestServicePort")
    public TestServicePortType getTestServicePort() {
        return super.getPort(TestServicePort, TestServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestServicePortType
     */
    @WebEndpoint(name = "TestServicePort")
    public TestServicePortType getTestServicePort(WebServiceFeature... features) {
        return super.getPort(TestServicePort, TestServicePortType.class, features);
    }

}
